# Generated by Django 5.0 on 2024-04-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_delete_userprofile'),
    ]

    operations = [
    ]
