# Generated by Django 5.0.4 on 2024-04-12 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_user"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
