# Generated by Django 5.0.4 on 2024-04-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="password",
            field=models.CharField(max_length=255),
        ),
    ]
